import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';

declare let self: ServiceWorkerGlobalScope;

// Precache app shell (generated by Vite PWA)
precacheAndRoute(self.__WB_MANIFEST);

// API calls: Network first, fallback to cache if offline
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/') ||
               url.pathname.startsWith('/process') ||
               url.pathname.startsWith('/get-tags'),
  new NetworkFirst({
    cacheName: 'api-cache',
    networkTimeoutSeconds: 10,
  })
);

// Video downloads: Network first (videos are large, don't cache aggressively)
registerRoute(
  ({ url }) => url.pathname.startsWith('/download/'),
  new NetworkFirst({
    cacheName: 'video-cache',
    networkTimeoutSeconds: 30,
  })
);

// Images: Cache first for performance
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images-cache',
  })
);

// Fonts: Stale while revalidate
registerRoute(
  ({ request }) => request.destination === 'font',
  new StaleWhileRevalidate({
    cacheName: 'fonts-cache',
  })
);
